# Generated by Django 4.0.5 on 2022-07-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_alter_place_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(db_column='latitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='long',
            field=models.FloatField(db_column='longitude'),
        ),
    ]
