# Generated by Django 4.0.5 on 2022-07-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_alter_place_lat_alter_place_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='state',
            field=models.BooleanField(choices=[(0, 'Active'), (1, 'Booked')], default=0),
        ),
    ]
