# Generated by Django 4.0.5 on 2022-07-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0006_hobby_friend_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='subjects',
            field=models.ManyToManyField(to='friends.hobby'),
        ),
    ]
