# Generated by Django 4.0.5 on 2022-07-13 17:41

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0008_friend_lower_name_age_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='friend',
            index=models.Index(django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('age'), '*', django.db.models.expressions.Value(365)), name='age_in_days_idx'),
        ),
    ]
