# Generated by Django 4.0.5 on 2022-07-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0010_alter_friend_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('name', 'lat', 'long')},
        ),
    ]
