# Generated by Django 4.0.5 on 2022-07-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0011_alter_place_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set(),
        ),
    ]
