# Generated by Django 4.0.5 on 2022-07-18 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0012_alter_place_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField(db_column='latitude')),
                ('long', models.FloatField(db_column='longitude')),
                ('type', models.CharField(choices=[('Pub', 'Pub'), ('Restaurant', 'Restaurant')], max_length=16)),
                ('subjects', models.ManyToManyField(to='friends.hobby')),
            ],
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('friends.establishment',),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('friends.establishment',),
        ),
        migrations.AlterField(
            model_name='friend',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='friends.establishment'),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
