# Generated by Django 4.0.5 on 2022-07-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0013_establishment_pub_restaurant_alter_friend_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('friend_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='friends.friend')),
                ('desired_order_value', models.IntegerField()),
            ],
            bases=('friends.friend',),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('friend_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='friends.friend')),
                ('max_guest_bill', models.IntegerField()),
            ],
            bases=('friends.friend',),
        ),
    ]
