# Generated by Django 4.0.5 on 2022-07-18 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0014_guest_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback', models.TextField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends.friend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstablishmentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback', models.TextField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends.establishment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
