# Generated by Django 4.0.5 on 2022-07-18 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0015_friendrating_establishmentrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends.guest')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends.host')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends.establishment')),
            ],
        ),
    ]
