# Generated by Django 4.0.5 on 2022-07-27 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0016_arrangement'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('friend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='friends.friend')),
            ],
        ),
    ]
