# Generated by Django 4.0.5 on 2022-08-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0017_friendprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='max_visitors',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='establishment',
            name='visitor_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
