# Generated by Django 4.0.5 on 2022-08-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0018_establishment_max_visitors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishmentrating',
            name='photo',
            field=models.ImageField(null=True, upload_to='raing_photoes'),
        ),
        migrations.AddField(
            model_name='friendrating',
            name='photo',
            field=models.ImageField(null=True, upload_to='raing_photoes'),
        ),
    ]
