# Generated by Django 4.0.5 on 2022-09-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0019_establishmentrating_photo_friendrating_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
    ]
