# Generated by Django 4.0.5 on 2022-09-21 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0020_queueplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishmentrating',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='raing_photoes'),
        ),
        migrations.AlterField(
            model_name='friendrating',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='raing_photoes'),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='ArrangementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends.arrangement')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends.menuitem')),
            ],
        ),
    ]
